language: go

sudo: false

go_import_path: github.com/xetys/hetzner-kube

cache:
  directories:
    - vendor

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure

after_script:
  - make hard-cleanup

script:
  - go test -v ./...

jobs:
  include:
    - stage: E2E testing
      script:
        - go build
        - make preparare
        - make test-all
        - make cleanup
      go: 1.11.x
      if: env(HETZNER_API_KEY) IS present

    - stage: Build
      script:
        - echo "Build binary & deploying to GitHub releases ..."
        - make build
      go: 1.10.x

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file_glob: yes
  file: dist/*
  name: $TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
